 steps:
 - name: gcr.io/cloud-builders/gcloud
   args:
     - '-c'
     - >-
       gcloud version | grep SDK
   entrypoint: bash
 - name: gcr.io/cloud-builders/gcloud:410.0.0-slim
 - name: gcr.io/cloud-builders/gcloud
   args:
     - '-c'
     - >-
       gcloud version | grep SDK
   entrypoint: bash
