 steps:
 - name: gcr.io/cloud-builders/gcloud
   args:
     - '-c'
     - >-
       gcloud version | grep SDK
   entrypoint: bash
 - name: gcr.io/google.com/cloudsdktool/cloud-sdk:410.0.0
   id: 'install'
   entrypoint: gcloud
   args: ['install']
 - name: gcr.io/cloud-builders/gcloud
   args:
     - '-c'
     - >-
       gcloud version | grep SDK
   entrypoint: bash
