 steps:
 - name: gcr.io/cloud-builders/gcloud
   args:
     - '-c'
     - >-
       file=$(gsutil ls -l gs://bs-demo  | sort -k 2 | tail -n 2 | head -1 | grep -i .war | awk '{print $3}') && echo $file 
   entrypoint: bash
