 substitutions:
   _PROJECT_ID: cloudside-academy
   _ZONE: asia-south1-a
   _CUSTOM_IMAGE: tomcat-image
   _FILE: gs://bs-demo/SamplesW.war
 steps:
 - name: gcr.io/google.com/cloudsdktool/cloud-sdk:410.0.0
   args:
     - '-c'
     - >-
       file=$(gsutil ls -l gs://bs-demo  | sort -k 2 | tail -n 2 | head -1 | grep -i .war | awk '{print $3}') &&
       gcloud compute instances create tomcat-vm-$BUILD_ID --image=$_CUSTOM_IMAGE --machine-type=e2-medium --project=$_PROJECT_ID --zone=$_ZONE --metadata=startup-script='#! /bin/bash 
       gsutil cp -r $_FILE /opt/tomcat/webapps'
   entrypoint: bash
